name: Dev

on:
  push:
    branches:
      - feature-**

env:
  REGISTRY: ghcr.io
  ENVIRONMENT: nonprod
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.ref_name }}
  RELEASE: ${{ github.repository }}-${{ github.ref_name }}

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build . --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Push image
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  deploy:
    needs: build

    name: Deploy
    runs-on: ubuntu-latest
    container: "alpine/helm:3.7.1"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set kubeconfig
      - run: echo ${{ secrets.KUBECONFIG }} > ~/.kube/config

      - name: Deploy to AKS
        working-directory: helm
        run: |
          helm upgrade ${{ env.RELEASE }} ./chart \
            --install \
            --create-namespace \
            -n ${{ env.ENVIRONMENT }} \
            -f dev.values.yml \
            --set image.tag=${{ env.IMAGE_TAG }}
